#!/bin/bash
echo"hello world good mrg"
echo"welcome to the session"
echo"hello world good mrg"
echo"welcome to the session"
echo"hello world good mrg"
echo"welcome to the session"
echo"hello world good mrg"
echo"welcome to the session"
echo"hello world good mrg"
echo"welcome to the session"
